services:
  api:
    build:
      context: ..
      dockerfile: ./Presentation/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__WriteConnection=Host=db;Port=5432;Database=CommonBackendDB;Username=CommonBackendWrite;Password=admin123
      - ConnectionStrings__ReadConnection=Host=db;Port=5432;Database=CommonBackendDB;Username=CommonBackendRead;Password=admin123
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: CommonBackendDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
